# Generated by Django 3.0.8 on 2020-08-20 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_follow_posts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follow',
            name='no_followers',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='follow',
            name='no_following',
            field=models.IntegerField(default=0),
        ),
    ]
