# Generated by Django 3.0.8 on 2020-08-23 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0010_posts_follow_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='follow_info',
        ),
    ]
