# Generated by Django 3.0.8 on 2020-08-26 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0014_auto_20200826_1437'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likes',
            name='post',
        ),
        migrations.AddField(
            model_name='posts',
            name='x',
            field=models.ManyToManyField(blank=True, related_name='likes', to='network.likes'),
        ),
    ]
